import Header from "@/components/Header/Header";
import "./globals.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import localFont from "next/font/local";

const myFont = localFont({
  src: "./fonts/PretendardVariable.ttf",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="kr" className={myFont.className} >
      <body>{children}</body>
    </html>
  );
}
